baseurl = "https://www.balooga.com"
languageCode = 'en-us'
defaultcontentlanguage = "en"

title = 'Balooga.com'
theme = "hugo-coder"

paginations.pagerSize = 20

[markup.highlight]
style = "github-dark"

# [[params.contact]]
#   email = luke@balooga.com

[params]
    author = "Luke Crook"
    info = "Meh to the max"
    email = "luke@balooga.com"
    #info = "An infrequent developer of occasionally functional things"
    # footercontent = "Between a REPL and a hard place"

    description = "Luke Crook's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar-greyscale.png"
    # gravatar = "luke@balooga.com"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    dateformat = "January 2, 2006"

    hidecredits = false
    hidecopyright = false
    hideFooter = false

    since = 2003

    enableTwemoji = true

    colorScheme = "auto"
    hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[services]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/balooga/"

# [params.mastodon]
#   host = "social.lol" # Address of your Mastodon instance
#   username = "balooga" # Your username
#   statusID = "" # ID os the status (post) that comments should be related
#   purifyCDN = "" # CDN address of pointing to a Purify package

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
